In [ ]:
import pandas as pd

In [ ]:
article = pd.read_csv("news_articles.csv")
article = article['Content']

In [ ]:
article[0]

'At least 14 people died and 17 others were injured after a bus travelling from Hyderabad to Kakinada plunged into a canal from a bridge on the accident-prone stretch of the Hyderabad-Khammam highway in Telangana early Monday morning \nThe injured were admitted to the Government General Hospital for treatment \n\n\nSeven people died on the spot and the others succumbed to injuries while undergoing treatment at the hospital  The passengers belonged to the East and West Godavari districts of Andhra Pradesh \nThe bus  owned by private operator Yatra Genie  commenced its journey from Hyderabad at 11 30 p m  on Sunday  Khammam Superintendent of Police Shah Nawaz Khan was quoted by the Hindustan Times as saying \nThe accident happened around 2 30 a m  when the driver slammed the brakes to avoid a collision with another vehicle coming from the opposite direction on a bridge over Nagarjunsagar project left canal at Nayankangudem village in Khammam district  the daily reported  The bus hit the 

### Using Regular Expression to remove some ambiquity

In [ ]:
import re
def decontracted(phrase):
# specific
    phrase = re.sub(r"won’t", "will not", phrase)
    phrase = re.sub(r"can’t", "can not", phrase)

    # general
    phrase = re.sub(r"n\'t", " not", phrase)
    phrase = re.sub(r"\'re", " are", phrase)
    phrase = re.sub(r"\'s", " is", phrase)
    phrase = re.sub(r"\'d", " would", phrase)
    phrase = re.sub(r"\'ll", " will", phrase)
    phrase = re.sub(r"\'t", " not", phrase)
    phrase = re.sub(r"\'ve", " have", phrase)
    phrase = re.sub(r"\'m", " am", phrase)
    return phrase

In [ ]:
for line in article:
    decontracted(line)

In [ ]:
article.apply(decontracted)

0       At least 14 people died and 17 others were inj...
1       TV actress Pratibha Tiwari  who is best known ...
2       The United States and South Korea began a join...
3       The relentless drive by Bengaluru s  Bangalore...
4       Punjab Gau Raksha Dal chief Satish Kumar and h...
5       Philippines police on Monday said that the num...
6       Infosys shares could fall sharply on Tuesday w...
7       Prime Minister Narendra Modi has expressed dee...
8       A school bus in the town of Bishnah in Jammu s...
9       A school bus carrying around 50 children fell ...
10      At least eight schoolchildren were killed when...
11      UPDATE  2 35 p m  IST   The death toll has ris...
12      Two students died while over 40 were electrocu...
13      Twelve people died and at least eight were inj...
14      The death toll in the bridge collapse near Mah...
15      4 30 p m  IST   Maharashtra Chief Minister Dev...
16      At least four more bodies were recovered from ...
17      A Brit

In [ ]:
article[0]

'At least 14 people died and 17 others were injured after a bus travelling from Hyderabad to Kakinada plunged into a canal from a bridge on the accident-prone stretch of the Hyderabad-Khammam highway in Telangana early Monday morning \nThe injured were admitted to the Government General Hospital for treatment \n\n\nSeven people died on the spot and the others succumbed to injuries while undergoing treatment at the hospital  The passengers belonged to the East and West Godavari districts of Andhra Pradesh \nThe bus  owned by private operator Yatra Genie  commenced its journey from Hyderabad at 11 30 p m  on Sunday  Khammam Superintendent of Police Shah Nawaz Khan was quoted by the Hindustan Times as saying \nThe accident happened around 2 30 a m  when the driver slammed the brakes to avoid a collision with another vehicle coming from the opposite direction on a bridge over Nagarjunsagar project left canal at Nayankangudem village in Khammam district  the daily reported  The bus hit the 

In [ ]:
def stripunc(X):
    return re.sub('[^A-Za-z]+', ' ', str(X), flags=re.MULTILINE|re.DOTALL)

In [ ]:
articles = article.apply(stripunc)
articles[1]

'TV actress Pratibha Tiwari who is best known for her role in Saath Nibhana Saathiya was molested by a stranger on a busy road in Mumbai It has been reported that Pratibha was waiting for a colleague along with her hairdresser when a drunk man came and molested the actress The incident happened at p m However the Saath Nibhana Saathiya fought back and dragged the accused to a nearby police station She has filed an FIR against the alleged molester Pratibha also expressed shock at anyone daring to misbehave with a girl It is surprising that such an incident could occur on a busy road at pm It was shocking but a revelation too I have learnt that women are scared to lodge a complaint in such cases but I would urge them to fight it out she told the Times of India The actress came to limelight with a show titled Tujhse Naraz Nahi Zindagi and had done a number of commercials She plays the character of Navya which has a negative shade in Saath Nibhana Saathiya http www ibtimes co in pratibha t

In [ ]:
type(articles)

pandas.core.series.Series

### Using NLTK

In [ ]:
# articles = articles.str.split(" ")
# articles
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

### Lemmatizing

In [ ]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

articles.apply(lambda x : " ".join([lemmatizer.lemmatize(word, pos="v") for word in x.split(" ")]))
# for line in articles
#     line = " ".join(lemmatizer.lemmatize(line.split(" "),pos='v'))
# articles[1]

0       At least people die and others be injure after...
1       TV actress Pratibha Tiwari who be best know fo...
2       The United States and South Korea begin a join...
3       The relentless drive by Bengaluru s Bangalore ...
4       Punjab Gau Raksha Dal chief Satish Kumar and h...
5       Philippines police on Monday say that the numb...
6       Infosys share could fall sharply on Tuesday wh...
7       Prime Minister Narendra Modi have express deep...
8       A school bus in the town of Bishnah in Jammu s...
9       A school bus carry around children fell into a...
10      At least eight schoolchildren be kill when an ...
11      UPDATE p m IST The death toll have rise to aft...
12      Two students die while over be electrocute on ...
13      Twelve people die and at least eight be injure...
14      The death toll in the bridge collapse near Mah...
15       p m IST Maharashtra Chief Minister Devendra F...
16      At least four more body be recover from the di...
17      A Brit

## TF-IDF scratch

In [ ]:
bog = []
len(bog)
for i in range(0,4831):
     #bog[i] = (articles[i].split(" "))
    bog.append(articles[i].split(" "))


In [ ]:
len(bog)

4831

In [ ]:
d={'Articles':articles,'bog':pd.Series(bog)}     
df = pd.DataFrame(d)
df


Articles  \
0     At least people died and others were injured a...   
1     TV actress Pratibha Tiwari who is best known f...   
2     The United States and South Korea began a join...   
3     The relentless drive by Bengaluru s Bangalore ...   
4     Punjab Gau Raksha Dal chief Satish Kumar and h...   
5     Philippines police on Monday said that the num...   
6     Infosys shares could fall sharply on Tuesday w...   
7     Prime Minister Narendra Modi has expressed dee...   
8     A school bus in the town of Bishnah in Jammu s...   
9     A school bus carrying around children fell int...   
10    At least eight schoolchildren were killed when...   
11    UPDATE p m IST The death toll has risen to aft...   
12    Two students died while over were electrocuted...   
13    Twelve people died and at least eight were inj...   
14    The death toll in the bridge collapse near Mah...   
15     p m IST Maharashtra Chief Minister Devendra F...   
16    At least four more bodies were recovered from ...   
17    A British era bridge in Maharashtra collapsed ...   
18    At least four people were killed and one injur...   
19    At least seven children died on Monday after a...   
20    In a tragic incident on Sunday as many as eigh...   
21    Five people died and were injured after a truc...   
22    At least people mostly tourists from China die...   
23    A BMW car driven by a Rajasthan MLA s son susp...   
24    A fire broke out at Mantralaya the Maharashtra...   
25    One person died and five others were injured a...   
26    A forensic report by Central Forensic Science ...   
27    Anton Yelchin who was best known for portrayin...   
28    Actress Pranitha Subhash met with an accident ...   
29    Update a m IST The police said the driver lost...   
...                                                 ...   
4801         India s rank in the Doing Business Report    
4802  The Chinese government bought shares worth bil...   
4803  Even as the global stock markets tumbled to mu...   
4804  Reports of Bollywood superstar Amitabh Bachcha...   
4805  Global rating agency Moody s Investors Service...   
4806  Earning upgrades would propel the S P BSE Sens...   
4807  The Chinese stock markets have fallen sharply ...   
4808  Although the domestic stock markets have witne...   
4809  Things seem to be getting worse for precious m...   
4810  Gold prices are estimated to decline further t...   
4811  Domestic jewellery maker Rajesh Exports Ltd RE...   
4812  Ahead of its official launch in India ASUS arr...   
4813  If you are out shopping for a budget smartphon...   
4814  The much hyped Asus Zenfone is all set to hit ...   
4815  Even today personal computers PCs are preferre...   
4816  In the Indian smartphone market Motorola s Mot...   
4817  IT security company ESET has recently released...   
4818  The GSM Association or GSMA association of mob...   
4819  Samsung has launched their latest flagship Sam...   
4820  The D printing technology has undergone lots o...   
4821  Known as the Mecca of smartphones lovers the M...   
4822  Samsung has finally launched its much awaited ...   
4823  HTC has launched its latest flagship smartphon...   
4824  Smartphone leader Samsung on Monday March offi...   
4825  Apple s iPhone and iPhone Plus have been domin...   
4826  Apple won its share of fame when it launched i...   
4827  HTC launched One M at MWC few days back Unlike...   
4828  Samsung s critically acclaimed Galaxy S and Ga...   
4829  Google has finally released the Android Lollip...   
4830  Apple is now the largest smartphone company in...   

                                                    bog  
0     [At, least, people, died, and, others, were, i...  
1     [TV, actress, Pratibha, Tiwari, who, is, best,...  
2     [The, United, States, and, South, Korea, began...  
3     [The, relentless, drive, by, Bengaluru, s, Ban...  
4     [Punjab, Gau, Raksha, Dal, chief, Satish, Kuma...  
5     [Philippines, police, on, Monday, 

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
cv.fit_transform(articles)
print(len(cv.get_feature_names()))

35322


In [ ]:
WordSet = set()
for line in bog:
    WordSet = set(WordSet).union(set(line))

In [ ]:
WordDict1 = dict.fromkeys(WordSet,0) 
WordDict2 = dict.fromkeys(WordSet,0)

In [ ]:
# bog[0]

In [ ]:
for word in bog[0]:
    WordDict1[word]+=1

for word in bog[1]:
    WordDict2[word]+=1

In [ ]:
def ComputeTF(WordDict, bow):
    tfDict = {}
    bowCount = len(bow)
    for word, count in WordDict.items():
        tfDict[word] = count / float(bowCount)
    return tfDict

In [ ]:
tfBow1 = ComputeTF(WordDict1,bog[0])
tfBow2 = ComputeTF(WordDict2,bog[0])

In [ ]:
# tfBow1

In [ ]:
def ComputeIDF(docList):
    import math
    idfDict={}
    N = len(docList)
    
    idfDict = dict.fromkeys(docList[0].keys(),0)
    for doc in docList:
        for word, value in doc.items():
            if value > 0:
                idfDict[word]+=1
    
    for word, value in idfDict.items():
        if value != 0:
            idfDict[word] = math.log(N / float(value))
        else:
            idfDict[word] = 0
    return idfDict


In [ ]:
idfs = ComputeIDF([WordDict1,WordDict2])

In [ ]:
def ComputeTFIDF(tfBow, idfs):
    tfidf = {}
    for word, value in tfBow.items():
        tfidf[word] = value * idfs[word]
        
    return tfidf

In [ ]:
ifidfBowA = ComputeTFIDF(tfBow1,idfs)
ifidfBowB = ComputeTFIDF(tfBow2,idfs)

### Bag Of Words

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()

In [ ]:
final_count = vect.fit_transform(articles.values)

In [ ]:
final_count.get_shape()

(4831, 35322)

In [ ]:
final_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
names = vect.get_feature_names()

In [ ]:
from sklearn.cluster import KMeans
Kmean = KMeans(n_clusters=2)
Kmean.fit_transform(final_count)

array([[23.82060295, 20.81160685],
       [16.48878668, 29.7767153 ],
       [19.25039152, 25.2437416 ],
       ...,
       [29.63777445, 24.51721288],
       [28.40605933, 29.52802276],
       [17.79227862, 28.77046138]])

Kmean.cluster_centers_

In [ ]:
Kmean.labels_

array([1, 0, 0, ..., 1, 0, 0], dtype=int32)

In [ ]:
lines = ['At least 14 people died and 17 others were injured after a bus travelling from Hyderabad to Kakinada plunged into a canal from a bridge on the accident-prone stretch of the Hyderabad-Khammam highway in Telangana early Monday morning \nThe injured were admitted to the Government General Hospital for treatment']
Kmean.predict(vect.transform(lines))


array([0], dtype=int32)

 ### Word2Vec

In [ ]:
from gensim.models import Word2Vec

In [ ]:
import gensim

In [ ]:
i=0
list_of_sent = []
for sent in articles.values:
  fil_sent = []
  for w in sent.split():
    for cleaned_words in w.split():
      if(cleaned_words.isalpha()):
        fil_sent.append(cleaned_words.lower())
      else:
        continue
    list_of_sent.append(fil_sent)
  

In [ ]:
print(articles[0])
print("-------------------------------")
print(list_of_sent[0])

At least people died and others were injured after a bus travelling from Hyderabad to Kakinada plunged into a canal from a bridge on the accident prone stretch of the Hyderabad Khammam highway in Telangana early Monday morning The injured were admitted to the Government General Hospital for treatment Seven people died on the spot and the others succumbed to injuries while undergoing treatment at the hospital The passengers belonged to the East and West Godavari districts of Andhra Pradesh The bus owned by private operator Yatra Genie commenced its journey from Hyderabad at p m on Sunday Khammam Superintendent of Police Shah Nawaz Khan was quoted by the Hindustan Times as saying The accident happened around a m when the driver slammed the brakes to avoid a collision with another vehicle coming from the opposite direction on a bridge over Nagarjunsagar project left canal at Nayankangudem village in Khammam district the daily reported The bus hit the parapet wall of the bridge and nose di

In [ ]:
w2v_model = gensim.models.Word2Vec(list_of_sent,min_count=5,size=50)

In [ ]:
words = list(w2v_model.wv.vocab)
print(len(words))

35346


## TF _IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(ngram_range=(1,1))
finnal = tfidf.fit_transform(articles.values)

In [ ]:
finnal.get_shape()

(4831, 35322)

In [ ]:
features = tfidf.get_feature_names()
print(len(features))

35322


In [ ]:
# average Word2Vec
import numpy as np
# compute average word2vec for each review.
sent_vectors_test = []; # the avg-w2v for each sentence/review is stored in this list
for sent in list_of_sent: # for each review/sentence
    sent_vec = np.zeros(50) # as word vectors are of zero length 50, you might need to change this to 300 if you use google's w2v
    cnt_words =0; # num of words with a valid vector in the sentence/review
    for word in sent: # for each word in a review/sentence
        if word in w2v_words:
            vec = w2v_model.wv[word]
            sent_vec += vec
            cnt_words += 1
    if cnt_words != 0:
        sent_vec /= cnt_words
    sent_vectors_test.append(sent_vec)
sent_vectors_test = np.array(sent_vectors_test)
print(sent_vectors_test.shape)
print(sent_vectors_test[0])

NameError: ignored

### TF-IDf weighted vector
 

In [ ]:
features = tfidf.get_feature_names()

tfidf_sent_vectors=[]
row = 0
for sent in list_of_sent:
  sent_vec =  np.zeros(50)
  weighted_sum = 0
  for word in sent:
    try:
      vec = w2v_model.wv[word]
      # obtain tfidf of that word
      tfidf = finnal[row,features.index(word)]
      sent_vec =+ (vec * tfidf)
      weighted_sum =+ tf_idf
    except:
      pass
    sent_vec /= weighted_sum
    tfidf_sent_vectors.append(sent_vec)
    row += 1


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:17: RuntimeWarning: divide by zero encountered in true_divide
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:17: RuntimeWarning: invalid value encountered in true_divide


## KMEANS


In [ ]:
Kmean = KMeans(n_clusters=2)
Kmean.fit_transform(tfidf_sent_vectors)

In [ ]:
Kmean.labels_